### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by sumitkharche**
- Added License badge
- Added table content in readme

### CODE REVIEW

**Comment by sumitkharche** [comment]
@eukreign Are these changes invalid?

**Comment by eukreign** [comment]
@sumitkharche see: https://github.com/lbryio/lbry-sdk/pull/2514

**Comment by sumitkharche** [comment]
> @sumitkharche see: #2514

Okay. Thanks @eukreign

**Comment by sumitkharche** [comment]
@eukreign As per comment in #2514 table is not valid here because of shot content. So can I add separate PR to add License badge? or license badge is also not necessary here.

**Comment by eukreign** [comment]
The license is already visible at the top of the page in the info bar provided by github.

**Pull request closed without merging**
