### PR TITLE
Support with comments

### LINKED ISSUE #3203: Pass custom text along with support
use case: adding a note to a support. in the app, you might see this if you mouse over a tip your received

- [ ] add tests
- [ ] add `note` field to signed support protobuf
- [ ] add `note` as input field to `support_create` api
- [ ] add `note` to any apis that return supports (e.g. txo_list)

### PR DESCRIPTION
**Pull request by shyba**
closes #3203

### CODE REVIEW

**Comment by kauffj** [comment]
I'm fine with disallowing anonymous supports for now, especially if it's easier to do so

**Comment by shyba** [comment]
tests are unstable due other issues with the tests themselves, will be fixed in another PR (re-run should make it pass for now)

**Review by eukreign — APPROVED** [review]

**Comment by meakba** [comment]
> closes #3203

**Comment by meakba** [comment]
https://github.com/lbryio/lbry-sdk/pull/3315#issue-658556830

**Comment by meakba** [comment]
Duplicate of #3339

**Review by meakba — COMMENTED** [review]
Duplicate of #

**Pull request merged**
