### PR TITLE
[WIP] check proofs from resolve where appropriate (blocked by lbrycrd release)

### PR DESCRIPTION
**Pull request by shyba**
depends on latest (unreleased) lbrycrd for all tests to be green

### CODE REVIEW

**Comment by lyoshenka** [comment]
victor is gonna ask brannon if lbrycrd bug is fixed

**Comment by lyoshenka** [comment]
brannon said he looked into it and couldn't find a problem on their end.

**Comment by eukreign** [comment]
@shyba what's the status on this? can you sync with @BrannonKing

**Comment by eukreign** [comment]
discussed with @shyba, we're going to close this for now until we have a better plan of using (or not using) lbrycrd as a python library in wallet server

**Pull request closed without merging**
