### PR TITLE
fix claim_search rpc and cli behaving differently

### PR DESCRIPTION
**Pull request by jackrobison**
don't autopopulate order_by in the server, instead populate an empty list in the client (which is what cli already did)

### CODE REVIEW

**Comment by lyoshenka** [comment]
@jackrobison does this need to be reviewed? plz request a review (or request from @lbryio/protocools if you're not sure whom to ask)

**Comment by eukreign** [comment]
i reviewed this in slack, will copy/paste it here as well

**Comment by eukreign** [comment]
@jackrobison after reflecting on this more, i think this PR should really just be to remove the default order_by, so just removing these two lines and fixing any tests that may fail expecting the default to be used (not sure if there are any tests that expect the default...):
https://github.com/lbryio/lbry-sdk/blob/0d08858dfb5178056fc1ad4c5afc3d4c1bfff511/lbry/wallet/server/db/reader.py#L421-L422

**Comment by eukreign** [comment]
done in https://github.com/lbryio/lbry-sdk/pull/2810

**Pull request closed without merging**
