### PR TITLE
updates HLS .m3u8 media type and adds new DASH .mpd media type

### PR DESCRIPTION
**Pull request by DispatchCommit**
HLS uses a playlist .m3u8 file to provide video content Transport Segments (.ts) files.
DASH uses a playlist .mpd file to provide video content of a few different containers.

Implementation of fixes as outlined in this thread on slack: https://lbryians.slack.com/archives/CCE20EWPQ/p1593702215379100

Fixes the m3u8 filetype, and adds the missing mpd file type. Video.js has full support for both.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Thanks for the PR! Can we show you some [appreciation](https://lbry.com/faq/appreciation) ?

**Comment by DispatchCommit** [comment]
@tzarebczan Even for what is in reality just a 2 line PR, it's amazing that anyone noticed, let alone jumped in to say thanks for it. 
But thank you for supporting and appreciation work put in from the community and supporting things in more than just one way. That's a personal touch you don't see all too often 😁 Thank you!

**Comment by DispatchCommit** [comment]
https://github.com/DispatchCommit/lbry-sdk/pull/1

image

Not sure why this wants to run into so many issues here 🙄 Passed successfully on my repo

**Comment by DispatchCommit** [comment]
So just to be clear, since it's passing in my repo, and there are known issues with the CI/CD toolchain, *and* there's a bug with one of the tooling systems used on the current pipeline, *AANNDDD* Python 3.8 support for pyinstaller is in a PR currently, 

There's nothing else I can think to do that would fix the CI/CD pipeline (I already patched it in the PR), but it's more than a single issue at this point. I'd prefer to not fuss with the 3.7 pipeline if the plan is to replace it with 3.8 here shortly, and from what I can tell, it's functional and passing.

Is there anything additional needed from me for this PR? There's sadly not much else I can do on the library network testing wise with the current mimetypes, as this is a blocker for what I was interested in exploring further.

**Comment by DispatchCommit** [comment]
bump :)

**Comment by kauffj** [comment]
Apologies for the delay on an ack here @DispatchCommit. Thank you for your efforts at this.

If @eukreign doesn't ack soon, I will bring it up with him in our meeting tomorrow.

**Comment by eukreign** [comment]
what does ack mean?

**Comment by DispatchCommit** [comment]
Acknowledge 😁

**Pull request merged**
