### PR TITLE
Fix checking protocol version

### PR DESCRIPTION
**Pull request by ben221199**
This pull request fixes issue #3738.

### CODE REVIEW

**Review by dziuplinhel — APPROVED** [review]

**Comment by ben221199** [comment]
In addition, the code was added by @jackrobison in https://github.com/lbryio/lbry-sdk/commit/1bf51e855d35013feb8a079153a913e1965f52a9.

**Comment by ben221199** [comment]
The commit was made after tagging `v0.53.2`, so the bug got released in `v0.53.3`.

If someone wants to write a LBRY hub themselves, note that `v0.53.2` doesn't have the bug, `v0.53.3` to `v0.113.0` have the bug, and if this pull request gets tagged as `v0.114.0`, from that version onwards the bug should be fixed.

**Comment by ben221199** [comment]
Hi @shyba, can you rerun the workflows again from here? It seemed they stopped and even disappeared.

**Comment by ben221199** [comment]
Merge please 🙂

**Review by shyba — APPROVED** [review]

**Comment by ben221199** [comment]
❤️

**Pull request merged**
