### PR TITLE
use more specific asserts in torba tests

### PR DESCRIPTION
**Pull request by StrikerRUS**
Use `assertListEqual`/`assertTupleEqual`/`assertDictEqual` instead of `asserEqual`.
This PR doesn't conflict with #2498, in which `assertTrue`/`assertFalse` replaces `assertEqual`.

### CODE REVIEW

**Comment by eukreign** [comment]
I would like to keep the no-spaces `20*CENT` version of amounts because it acts as a sort of domain specific language in the tests. Can you change the amount back to no-spaces and also please rebase the PR.

**Comment by StrikerRUS** [comment]
@eukreign Thanks for your review! I wanted just to make those lines consistent with 
https://github.com/lbryio/lbry-sdk/blob/077281a77a82cfdfca0ec02922d4e582233bae43/torba/tests/client_tests/unit/test_coinselection.py#L66-L69

I'm sorry about that! I've just reverted back my changes related to spaces around `*` operator. Please check it.

**Comment by StrikerRUS** [comment]
I've just commited the same changes for `integration` folder in `torba`.

**Comment by eukreign** [comment]
@StrikerRUS okay, looks good now, before I merge this can you explain the pros/cons of the plain assertEqual vs the specific ones? what benefits does this PR bring over what was there before?

For example:
```python
        self.assertEqual(network.client.server, ('127.0.0.1', 1337))
        self.assertTupleEqual(network.client.server, ('127.0.0.1', 1337))
```

Is there a case where a plain `assertEqual` would not catch something that `assertTupleEqual` does catch?

**Comment by StrikerRUS** [comment]
@eukreign Sure! The obvious advantage of using specific tests that you cannot change any API without changing the corresponding test. Also, such asserts increase readability a lot and remove costs of the need to detect appropriate assert inside simple `assertEqual`.

For instance, you'll not be able to simply change `self.assertEqual(foo(), ('one', 'two'))` to `self.assertEqual(foo(), ('one'))`

**Comment by tzarebczan** [comment]
@StrikerRUS Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

Also, we're giving away some [Hacktoberfest](https://lbry.com/news/hacktoberfest-2019) bonuses and goodies for this month.

**Pull request merged**
