### PR TITLE
Add no_totals argument to claim search

### PR DESCRIPTION
**Pull request by patrickkeane**

### CODE REVIEW

**Comment by eukreign** [comment]
Does passing `--no_totals` do anything different? If I recall correctly the feature was dropped to return totals in the first place so `--no_totals` is redundant I think.

**Comment by patrickkeane** [comment]
Code exists throughout the SDK to support totals (and use of `--no_totals` flag), including in `jsonrpc_claim_search`.  Do you mean that the feature of `--no_totals` throughout the code was dropped, or specific to `claim_search`?  Neither is true, as far as I see.

The result structure is appended with totals unless the flag is used, with the submitted PR.  See below:

```
(lbry-venv) patrick@illuminati:~/Development/lbry/lbry-sdk$ lbrynet claim search | tail -10
        "title": "Life in the Iron-Mills; Or, The Korl Woman"
      },
      "value_type": "stream"
    }
  ],
  "page": 1,
  "page_size": 20,
  "total_items": 9910688,
  "total_pages": 495535
}
(lbry-venv) patrick@illuminati:~/Development/lbry/lbry-sdk$ lbrynet claim search --no_totals | tail -10
        },
        "stream_type": "binary",
        "title": "Life in the Iron-Mills; Or, The Korl Woman"
      },
      "value_type": "stream"
    }
  ],
  "page": 1,
  "page_size": 20
}
(lbry-venv) patrick@illuminati:~/Development/lbry/lbry-sdk$
```

**Comment by eukreign** [comment]
@patrickkeane thank you for this PR, please follow these instructions so that we can show you some appreciation: https://lbry.com/faq/appreciation

**Comment by patrickkeane** [comment]
Perhaps issue #2788 can be closed.

**Comment by eukreign** [comment]
> Perhaps issue #2788 can be closed.

In the future if you put "fixes #2788" in the description of your PR the issue will automatically be closed when your PR is merged.

**Pull request merged**
