### PR TITLE
Adds spend_address param to support_abandon

### PR DESCRIPTION
**Pull request by osilkin98**
Allows you to specify a lbry wallet address to `support abandon` which receives the LBC released from the support transaction.

### CODE REVIEW

**Comment by lyoshenka** [comment]
@osilkin98 what's the next step here? does it need a review?

**Comment by tzarebczan** [comment]
Lex is aware of this one and wanted to do a deeper use case review.

**Comment by osilkin98** [comment]
Alright, I'll leave this one open just in case.

**Comment by lyoshenka** [comment]
Lex and Oleg discussed offline. Instead of adding this param, a better approach would be to add a new rpc call for the use case of sending a channel with a bunch of claims/supports to another address. `spend_address` has some corner cases that are hard to handle without that.

**Pull request closed without merging**
